name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write 
  pages: write
  id-token: write
  checks: write

jobs:
  running-cucumber-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Remove @current from .feature files
        run: find . -name "*.feature" -type f -print0 | xargs -0 sed -i -E 's/(^|\s)@current(\s|$)/\2/g'

      - name: Commit and push changes if needed
        run: |
          if ! git diff --quiet; then
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "GitHub Actions Bot"
            git add '*.feature'
            git commit -m "Remove @current tags from .feature files"
            git push
          fi

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber - Playwright tests
        run: npm test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: allure-report/
          retention-days: 30

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "allure-report/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
